'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { ForenzaLogo } from '@/components/brand/ForenzaLogo'
import { ThemeToggle } from '@/components/theme/ThemeToggle'
import { Shield, KeyRound, AlertCircle, Loader2, ArrowRight, Smartphone } from 'lucide-react'
import { toast } from 'sonner'

export default function MfaPage() {
  const router = useRouter()
  const [code, setCode] = useState(['', '', '', '', '', ''])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const handleChange = (index: number, val: string) => {
    if (val.length > 1) {
      // Paste handling
      const digits = val.replace(/\D/g, '').slice(0, 6).split('')
      const newCode = [...code]
      digits.forEach((d, i) => {
        newCode[i] = d
      })
      setCode(newCode)
      const nextInput = document.getElementById(`mfa-digit-${Math.min(digits.length, 5)}`)
      nextInput?.focus()
      return
    }

    const newCode = [...code]
    newCode[index] = val.replace(/\D/g, '')
    setCode(newCode)

    if (val && index < 5) {
      const nextInput = document.getElementById(`mfa-digit-${index + 1}`)
      nextInput?.focus()
    }
  }

  const handleKeyDown = (index: number, e: React.KeyboardEvent) => {
    if (e.key === 'Backspace' && !code[index] && index > 0) {
      const prevInput = document.getElementById(`mfa-digit-${index - 1}`)
      prevInput?.focus()
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    const fullCode = code.join('')
    if (fullCode.length !== 6) {
      setError('Please enter all 6 digits of your authentication code.')
      return
    }

    setLoading(true)
    setError(null)

    try {
      // Complete MFA session
      toast.success('MFA Verification Successful')
      router.push('/supervisor/dashboard')
    } catch {
      setError('Invalid authentication code. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-slate-50 dark:bg-[#0B0F19] text-slate-900 dark:text-slate-100 p-4 transition-colors relative">
      <div className="absolute top-4 right-4">
        <ThemeToggle />
      </div>

      <div className="w-full max-w-md">
        {/* Logo */}
        <div className="text-center mb-8">
          <ForenzaLogo size="lg" showTagline={true} className="justify-center mb-2" />
        </div>

        {/* MFA Box */}
        <div className="forenza-card p-6 sm:p-8 rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#111827] shadow-xl">
          <div className="flex items-center gap-2 mb-4 text-blue-600 dark:text-blue-400">
            <Smartphone className="w-5 h-5" />
            <span className="text-xs font-bold uppercase tracking-wider">
              MULTI-FACTOR AUTHENTICATION
            </span>
          </div>

          <h2 className="text-xl font-bold text-slate-900 dark:text-slate-100 tracking-tight">
            Security Verification Code
          </h2>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 mb-6">
            Enter the 6-digit TOTP code generated by your approved authenticator app or hardware token.
          </p>

          {error && (
            <div className="flex items-start gap-2.5 p-3.5 rounded-lg mb-6 bg-red-50 dark:bg-red-950/40 border border-red-200 dark:border-red-800/60 text-xs text-red-600 dark:text-red-300">
              <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
              <span>{error}</span>
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-6">
            {/* 6 Digit Inputs */}
            <div className="flex justify-between gap-2">
              {code.map((digit, index) => (
                <input
                  key={index}
                  id={`mfa-digit-${index}`}
                  type="text"
                  inputMode="numeric"
                  maxLength={1}
                  value={digit}
                  onChange={(e) => handleChange(index, e.target.value)}
                  onKeyDown={(e) => handleKeyDown(index, e)}
                  autoFocus={index === 0}
                  className="w-12 h-14 text-center font-mono text-xl font-extrabold rounded-xl bg-slate-50 dark:bg-[#0B0F19] border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-slate-100 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 outline-none transition-all"
                />
              ))}
            </div>

            <button
              type="submit"
              disabled={loading || code.some((d) => !d)}
              className="w-full py-3 rounded-xl font-bold text-sm bg-blue-600 hover:bg-blue-700 text-white transition-all shadow-md shadow-blue-600/30 flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>Verifying Token...</span>
                </>
              ) : (
                <>
                  <span>Verify Identity & Proceed</span>
                  <ArrowRight className="w-4 h-4" />
                </>
              )}
            </button>
          </form>

          <div className="mt-6 pt-4 border-t border-slate-100 dark:border-slate-800 text-center">
            <p className="text-[11px] text-slate-400 font-mono">
              SESSION PROTECTED BY FORENZA AUTH PROTOCOL v2.4
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
